correction: app crashes if command does not exist > broadlink-mqtt-bridge@1.0.0 start > node -r esm index.js
LOGLEVEL: warn
2022-02-25 18:36:53 [warn]:     Didn't find file C:\_projects_\broadlink-mqtt-bridge\commands\nexa\tv\button\on, try to load old version
C:\_projects_\broadlink-mqtt-bridge\src\actions\files.js:45
          reject(new Error(`Failed to load file ${pathToFile}`));
                 ^

Error: Failed to load file C:\_projects_\broadlink-mqtt-bridge\commands\nexa\tv\button\on
    at ReadFileContext.callback (C:\_projects_\broadlink-mqtt-bridge\src\actions\files.js:45:18)
    at FSReqCallback.readFileAfterOpen [as oncomplete] (node:fs:314:13)
The terminal process "C:\Program Files\Git\bin\bash.exe '--login', '-c', 'npm run start'" terminated with exit code: 1.